### PR TITLE
dutch translatation wako app

### PR DESCRIPTION
**Pull request by fransalmighty**
i translated the wako app in dutch language

### CODE REVIEW

**Comment by JumBay** [comment]
Thanks, I'll add it

**Comment by JumBay** [comment]
How do you say `dutch` in dutch? I will be the text to display when you want to select the dutch language

**Comment by fransalmighty** [comment]
Your welcome i did my best ;) wako is the best app i used thanx for all
your hard work

Op wo 28 okt. 2020 22:00 schreef Jean-Baptiste Malatrasi <
notifications@github.com>:

**Comment by fransalmighty** [comment]
Dutch is dutch ;) and we live in the Netherlands :p

Op wo 28 okt. 2020 22:02 schreef Jean-Baptiste Malatrasi <
notifications@github.com>:

**Comment by JumBay** [comment]
Thanks, dutch it will ben then ;)

**Comment by fransalmighty** [comment]
I know what you want haha sorry dutch is Nederlands

Op wo 28 okt. 2020 22:12 schreef Jean-Baptiste Malatrasi <
notifications@github.com>:

**Comment by fransalmighty** [comment]
Maybe you want my phonenumber for WhatsApp if you have some more questions

+31 630460334

Op wo 28 okt. 2020 22:12 schreef Jean-Baptiste Malatrasi <
notifications@github.com>:

**Comment by JumBay** [comment]
We use discord for this https://discord.gg/qbeM8v8

I recommend you to remove your phone number from github to avoid spam ;). 
Your response is public

**Comment by fransalmighty** [comment]
> We use discord for this https://discord.gg/qbeM8v8
> 
> I recommend you to remove your phone number from github to avoid spam ;).
> Your response is public

Thanx phone number deleted ;)

And i will take a look for Discord

**Pull request merged**
